.github/workflows/scratch-org-sfdx-ci-master.yml
force-app/main/default/staticresources/documentation/docs/docs/RestClient.md
force-app/main/default/staticresources/documentation/docs/docs/TriggerHandler.md

Added a step to fetch commit history prior to generating doc in CI.

Fix for CI doc generation

---

bin/orgInit.ps1
config/project-scratch-def.json

Incorporates SZandor72's changes that he made in PR26 into master. CI is failing on his PR because of Secrets not being available to his branch.
#26 
[x] Tests for the proposed changes have been added/updated.
[x] Code linting and formatting was performed.
Now with a windows powershell script mirroring bin/orgInit.sh as well as a modification to the scratch org definition that sets the language to english.

Incorporates Szandor72s changes in pr26

---

.github/workflows/scratch-org-sfdx-ci-pr.yml

Adds automated Security scans on PR.

feat: implement automated security scans with PMD

---

README.md

Added Trailhead badge in readme:

Added Trailhead badge in readme

---

README.md

Removed references to My Domain

---

force-app/main/default/classes/Shared Code/LogMessage.cls

No longer using sobject, but concreate log__e

Updates return type

---

.github/workflows/ci-pr-prerelease.yml
.github/workflows/ci-pr.yml
.github/workflows/ci.yml
.github/workflows/packaging-pr-prerelease.yml
.github/workflows/packaging-pr.yml
.github/workflows/packaging.yml

New CLI install URL and script

New CLI install script

---

force-app/main/default/lwc/formattedRecipeDisplay/__tests__/formattedRecipeDisplay.test.js
force-app/main/default/lwc/recipeTreeView/__tests__/recipeTreeView.test.js
package-lock.json
package.json

Closes #162
Updates code to new wire adapter syntax.

updates tests to new wire adapter logic. Closes Update LWC Jest and tests following wire protocol reform #162

---

force-app/main/default/classes/Safely_Tests.cls
force-app/main/default/classes/Safely_Tests.cls-meta.xml
force-app/main/default/classes/Security Recipes/CanTheUser.cls
force-app/main/default/classes/Security Recipes/Safely.cls
force-app/main/default/classes/Security Recipes/Safely.cls-meta.xml
force-app/tests/Shared Code/MetadataTriggerHandler_Tests.cls
force-app/tests/Shared Code/TestFactory.cls

Introduces Safely, a delightfully elegant library for ensuring DML is done, well, Safely.
Also includes unit tests and improvements to CanTheUser.

Adds Safely

---

force-app/main/default/lwc/formattedDocsViewer/__mocks__/formattedDocsViewer.js
force-app/main/default/lwc/formattedDocsViewer/__tests__/formattedDocsViewer.test.js
force-app/main/default/lwc/formattedDocsViewer/formattedDocsViewer.js

Provides additional Jest Tests

Additional Jest Tests

---

force-app/tests/CI Recipes/DeprecatedAPIVersionScanner_Tests.cls
force-app/tests/CI Recipes/DeprecatedAPIVersionScanner_Tests.cls-meta.xml

Introduces a Unit Test that fails if there is evidence of Deprecated / Legacy API Versions being used.

introduces CI-able test for deprecated api versions

---

force-app/main/default/classes/Collection Recipes/ListSortingRecipes.cls
force-app/main/default/classes/Collection Recipes/ListSortingRecipes.cls-meta.xml
force-app/main/default/classes/Collection Recipes/SortableAccount.cls
force-app/main/default/classes/Collection Recipes/SortableAccount.cls-meta.xml
force-app/main/default/classes/Shared Code/ListUtils.cls
force-app/main/default/classes/Shared Code/ListUtils.cls-meta.xml
force-app/main/default/classes/Shared Code/SObjectStringFieldComparator.cls
force-app/main/default/classes/Shared Code/SObjectStringFieldComparator.cls-meta.xml
force-app/main/default/staticresources/documentation/docs/docs/CanTheUser.md
force-app/main/default/staticresources/documentation/docs/docs/ListSortingRecipes.md
force-app/main/default/staticresources/documentation/docs/docs/ListUtils.md
force-app/main/default/staticresources/documentation/docs/docs/SObjectStringFieldComparator.md
force-app/main/default/staticresources/documentation/docs/docs/Safely.md
force-app/main/default/staticresources/documentation/docs/docs/Safely_Tests.md
force-app/main/default/staticresources/documentation/docs/docs/SortableAccount.md
force-app/tests/Collection Recipes/SObjectStringFieldComparator_Tests.cls
force-app/tests/Collection Recipes/SObjectStringFieldComparator_Tests.cls-meta.xml
force-app/tests/Collection Recipes/SortableAccount_Tests.cls
force-app/tests/Collection Recipes/SortableAccount_Tests.cls-meta.xml
force-app/tests/Shared Code/SObjectStringFieldComparator_Tests.cls
force-app/tests/Shared Code/SObjectStringFieldComparator_Tests.cls-meta.xml

This PR adds list sorting recipes under a collection recipes folder.
I'll add iterator recipes in that folder in a separate PR later.

feat: added list sorting recipes

---

package.json

Updated local Prettier to use `--check` command instead of `--list-different`.

Updated local Prettier to use 'check' command

---

force-app/main/default/classes/Email Recipes/InboundEmailHandlerRecipes.cls

Email Recipes Update

---

force-app/main/default/classes/Async Apex Recipes/BatchApexRecipes.cls
force-app/main/default/staticresources/documentation/docs/docs/BatchApexRecipes.md
force-app/tests/Testing Recipes/StubExample_Tests.cls

Update comments, No Functionality Changes

refactor: update comments

---

force-app/tests/Trigger Recipes/AccountTriggerHandler_Tests.cls
force-app/tests/Trigger Recipes/MetadataTriggerService_Tests.cls

feat: update system.asserts to use new Assert class - Trigger Recipes

---

force-app/tests/Shared Code/AccountServiceLayer_Tests.cls
force-app/tests/Shared Code/ApexClassUtilities_Tests.cls
force-app/tests/Shared Code/CollectionUtils_Tests.cls
force-app/tests/Shared Code/DataFactoryForPackageInstalls_Tests.cls
force-app/tests/Shared Code/FormattedRecipeDisplayController_Tests.cls
force-app/tests/Shared Code/Log_Tests.cls
force-app/tests/Shared Code/MetadataTriggerHandler_Tests.cls
force-app/tests/Shared Code/OrderAppMenu_Tests.cls
force-app/tests/Shared Code/OrgShape_Tests.cls
force-app/tests/Shared Code/RecipeTreeViewController_Tests.cls
force-app/tests/Shared Code/RelatedCodeTabsController_Tests.cls
force-app/tests/Shared Code/RestClient_Tests.cls
force-app/tests/Shared Code/TriggerHandler_Test.cls

feat: Update asserts to use new winter23 Assert class - Shared Code Recipes

---

force-app/tests/Security Recipes/CanTheUser_Tests.cls
force-app/tests/Security Recipes/Safely_Tests.cls
force-app/tests/Security Recipes/StripInaccessibleRecipes_Tests.cls

feat: Update asserts to use new winter23 Assert class - Security Recipes

---

force-app/tests/Testing Recipes/PSGTestingRecipes.cls
force-app/tests/Testing Recipes/StubExample_Tests.cls
force-app/tests/Testing Recipes/StubbingRecipes_Tests.cls

feat: Update asserts to use new winter23 Assert class - Testing Recipes

---

force-app/tests/Quiddity Recipes/QuiddityGuard_Tests.cls
force-app/tests/Quiddity Recipes/QuiddityRecipes_Tests.cls

feat: Update asserts to use new winter23 Assert class - Quiddity Recipes

---

force-app/tests/Platform Event Recipes/PlatformEventRecipesTriggerHandler_Tests.cls
force-app/tests/Platform Event Recipes/PlatformEventRecipes_Tests.cls

feat: Update asserts to use new winter23 Assert class - Platform Event Recipes

---

force-app/tests/Invocable Recipes/InvocableMethodRecipes_Tests.cls

feat: Update asserts to use new winter23 Assert class - Invocable Recipes

---

force-app/tests/Files Recipes/FilesRecipes_Tests.cls

feat: Update asserts to use new winter23 Assert class - Files Recipes

---

force-app/tests/Email Recipes/InboundEmailHandlerRecipes_tests.cls

feat: Update asserts to use new winter23 Assert class - Email Recipes

---

force-app/tests/Data Recipes/DMLRecipes_Tests.cls
force-app/tests/Data Recipes/DynamicSOQLRecipes_Tests.cls
force-app/tests/Data Recipes/MetadataCatalogRecipes_Tests.cls
force-app/tests/Data Recipes/SOQLRecipes_Tests.cls
force-app/tests/Data Recipes/SOSLRecipes_Tests.cls

feat: update system.asserts to use new Assert class - Data Recipes

---

force-app/tests/Custom Metadata Recipes/CustomMetadataRecipes_Tests.cls

feat: Update asserts to use new winter23 Assert class - Custom Metadata Recipes

---

force-app/tests/Collection Recipes/IterationRecipes_Tests.cls
force-app/tests/Collection Recipes/SObjectStringFieldComparator_Tests.cls
force-app/tests/Collection Recipes/SortableAccount_Tests.cls

feat: Update asserts to use new winter23 Assert class - Collection Recipes

---

force-app/tests/CI Recipes/DeprecatedAPIVersionScanner_Tests.cls

feat: Update asserts to use new winter23 Assert class - CI Recipes

---

force-app/tests/Async Apex Recipes/AtFutureRecipes_Tests.cls
force-app/tests/Async Apex Recipes/BatchApexRecipes_Tests.cls
force-app/tests/Async Apex Recipes/QueueableChainingRecipes_Tests.cls
force-app/tests/Async Apex Recipes/QueueableRecipes_Tests.cls
force-app/tests/Async Apex Recipes/QueueableWithCalloutRecipes_Tests.cls
force-app/tests/Async Apex Recipes/ScheduledApexDemo_Tests.cls
force-app/tests/Async Apex Recipes/ScheduledApexRecipes_Tests.cls

feat: Update asserts to use new winter23 Assert class - Async Recipes

---

force-app/tests/Integration Recipes/ApiServiceRecipesDataModel_Tests.cls
force-app/tests/Integration Recipes/ApiServiceRecipes_Tests.cls
force-app/tests/Integration Recipes/AuraEnabledRecipes_Tests.cls
force-app/tests/Integration Recipes/CalloutRecipes_Tests.cls
force-app/tests/Integration Recipes/CustomRestEndpointRecipes_Tests.cls

feat: Update asserts to use new winter23 Assert class - Integration Recipes

---

force-app/main/default/classes/Custom Metadata Recipes/CustomMetadataUtilties.cls
force-app/main/default/classes/Data Recipes/SOQLRecipes.cls
force-app/main/default/classes/Files Recipes/FilesRecipes.cls
force-app/main/default/classes/Integration Recipes/AuraEnabledRecipes.cls
force-app/main/default/classes/Integration Recipes/CalloutRecipes.cls
force-app/main/default/staticresources/documentation/docs/docs/AuraEnabledRecipes.md
force-app/main/default/staticresources/documentation/docs/docs/CalloutRecipes.md
force-app/main/default/staticresources/documentation/docs/docs/SOQLRecipes.md
force-app/tests/Integration Recipes/AuraEnabledRecipes_Tests.cls

This PR adds Spring 23 user mode data operations as applicable.
[ ✔] Tests for the proposed changes have been added/updated.
[ ] Code linting and formatting was performed -- BLOCKED Due to Prettier not being updated

feat: switched to user mode DB ops when applicable

---

force-app/main/default/classes/Data Recipes/DMLRecipes.cls
force-app/main/default/staticresources/documentation/docs/docs/DMLRecipes.md
force-app/tests/Data Recipes/DMLRecipes_Tests.cls

[ ✔] Tests for the proposed changes have been added/updated.
[ ] Code linting and formatting was performed -- BLOCKED Due to Prettier not being updated
This PR adds Spring 23 user mode data operations to the DML Recipes. Now we have dedicated recipes to show both the User Mode Database operations vs System mode.

feat: DML Recipe updates for sp23

---

force-app/tests/Shared Code/Log_Tests.cls

Fixes test error message reported in #401

fix: test error message

---

force-app/main/default/classes/Collection Recipes/AccountNumberOfEmployeesComparator.cls
force-app/main/default/classes/Collection Recipes/AccountShippingCountryComparator.cls
force-app/main/default/classes/Collection Recipes/ListSortingRecipes.cls
force-app/main/default/staticresources/documentation/AccountNumberOfEmployeesComparator.md
force-app/main/default/staticresources/documentation/AccountShippingCountryComparator.md
force-app/main/default/staticresources/documentation/ListSortingRecipes.md

Fixes some minor doc corrections after review from @albarivas 
[X] Tests for the proposed changes have been added/updated.
[X] Code linting and formatting was performed.

feat: fix minor issues

---

.github/workflows/auto-assign.yml
.github/workflows/ci-pr.yml
.github/workflows/ci.yml
.github/workflows/packaging-pr.yml
.github/workflows/packaging.yml
force-app/main/default/staticresources/documentation/AccountTriggerHandler.md
force-app/main/default/staticresources/documentation/BatchApexRecipes.md
force-app/main/default/staticresources/documentation/CsvData.md
force-app/main/default/staticresources/documentation/EncryptionRecipes.md
force-app/main/default/staticresources/documentation/FilesRecipes.md
force-app/main/default/staticresources/documentation/FormattedRecipeDisplayController.md
force-app/main/default/staticresources/documentation/InvocableMethodRecipes.md
force-app/main/default/staticresources/documentation/IterableApiClient.md
force-app/main/default/staticresources/documentation/LDVRecipes.md
force-app/main/default/staticresources/documentation/Log.md
force-app/main/default/staticresources/documentation/LogMessage.md
force-app/main/default/staticresources/documentation/LogTriggerHandler.md
force-app/main/default/staticresources/documentation/MetadataCatalogRecipes.md
force-app/main/default/staticresources/documentation/MetadataTriggerHandler.md
force-app/main/default/staticresources/documentation/NamedCredentialRecipes.md
force-app/main/default/staticresources/documentation/OrgShape.md
force-app/main/default/staticresources/documentation/PlatformEventRecipesTriggerHandler.md
force-app/main/default/staticresources/documentation/QueueableWithCalloutRecipes.md
force-app/main/default/staticresources/documentation/RecipeTreeViewController.md
force-app/main/default/staticresources/documentation/StubExample.md
force-app/main/default/staticresources/documentation/TestDouble.md
force-app/main/default/staticresources/documentation/TriggerHandler.md
package-lock.json
package.json

ci: upgrade to node@20
